server:
  port: ${PORT:8777}

application:
  name: forumservice
  description: forumservice
  development-mode: true

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}  # Adjust to match your database name
    username: ${SPRING_DATASOURCE_USERNAME}  # Adjust if your MySQL user is different
    password: ${SPRING_DATASOURCE_PASSWORD}    # If no password, leave it blank; otherwise, provide it here
    driver-class-name: com.mysql.cj.jdbc.Driver  # Add this line for MySQL driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update  # Change to validate/none for production environments

moderation:
  logging:
    enabled: true

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org.springframework: ${LOG_LEVEL:ERROR}
    org.hibernate: ${LOG_LEVEL:ERROR}
  pattern:
    console: "%level %d [%logger %M] : %replace(%msg){'\n','\u2028'} %replace(%xException){'\n','\u2028'}%nopex%n"
