name: Java CI/CD with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
           mvn clean install
           mkdir artifacts && cp target/*.jar artifacts
           cd artifacts && ls
    - name: Save artifact
      uses: actions/upload-artifact@v2
      with:
        name: github-action-artifact
        path: artifacts
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/jforum_forumservice:latest

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Pull Image from Docker Hub
  #     run: sudo docker pull mohibgazi/jforum_forumservice:latest

  #   - name: SSH to EC2 and deploy Docker container
  #     run: |
  #       # Ensure SSH key is added and EC2 access is available
  #       chmod 600 ${{ secrets.EC2_SSH_PRIVATE_KEY }}
  #       echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ec2_key.pem
  #       ssh -o StrictHostKeyChecking=no -i ec2_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
  #         # Stop the old container if exists
  #         sudo docker rm -f jforum_forumservice-container || true
  #         # Run the new Docker container with MySQL connection details as environment variables
  #         sudo docker run -d -p 8080:8080 --name jforum_forumservice-container \
  #           -e SPRING_DATASOURCE_URL=jdbc:mysql://${{ secrets.MYSQL_HOST }}:${{ secrets.MYSQL_PORT }}/${{ secrets.MYSQL_DB_NAME }} \
  #           -e SPRING_DATASOURCE_USERNAME=${{ secrets.MYSQL_USERNAME }} \
  #           -e SPRING_DATASOURCE_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
  #           mohibgazi/jforum_forumservice:latest
  #       EOF
