name: Java CI/CD with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
           mvn clean install -DskipTests 
           mkdir artifacts && cp target/*.jar artifacts
           cd artifacts && ls
    - name: Save artifact
      uses: actions/upload-artifact@v4
      with:
        name: github-action-artifact
        path: artifacts
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/jforum_forumservice:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Pull Image from Docker Hub
      run: sudo docker pull venkatsp17/jforum_forumservice:latest

    - name: SSH to EC2 and deploy Docker container
      run: |
        # Ensure SSH key is added and EC2 access is available
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ec2_key.pem
        chmod 600 ec2_key.pem  # Set correct permissions for the key
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          # Stop the old container if it exists
          sudo docker rm -f jforum_forumservice-container || true
    
          # Run the new Docker container with MySQL connection details as environment variables
          sudo docker run -d -p 8777:8777 --name jforum_forumservice-container \
            -e SPRING_DATASOURCE_URL="${{ secrets.DB_URL }}" \
            -e SPRING_DATASOURCE_USERNAME="${{ secrets.MYSQL_USERNAME }}" \
            -e SPRING_DATASOURCE_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
            venkatsp17/jforum_forumservice:latest
        EOF
    

